### PR TITLE
Workaholic: don't kill advice message option (if visible to everyone), `Can't win after they died`: default OFF

### PR DESCRIPTION
**Pull request by Filipianosol**
## Workaholic: New Option: Don’t Kill Advice (If Visible to Everyone)

https://user-images.githubusercontent.com/12639838/236742188-54d564e6-4194-44d3-93c7-baeb5a02f8c0.mp4

I felt notifying about Workaholic every meeting could be a bit
unnecessary so I've chosen to only send the message at first meeting.
This can always be changed to every meeting if [@KARPED1EM](https://github.com/KARPED1EM) wishes so.

Note:
The message doesn't appear if `Ghosts Exempt From Tasks` is ON. This is
because Workaholic doesn't win upon death then, even if
`Can't win after they died` is OFF.

I couldn't figure out how to spawn more than one Workaholic so I haven't
tested with multiple but it should list all alive Workaholic player
names in the message, just like it does with one Workaholic.

Non-English strings need to be translated.

## Workaholic: Can’t Win after They Died: Default OFF
On the current default settings Workaholic doesn't stand a chance.

By default everyone can see who the Workaholic is. Because of this,
players can rush to hunt them down or vote them off and there is no
punishment for doing so, as by default they can't win once they've died.
You could override their tasks to 2 or 3 to give them a chance but then
it becomes a ridiculous role that dies/wins too quickly in my opinion,
like a worse version of YouTuber.

This is why instead I'm proposing `Can't win after they died` be set to
OFF by default. I believe default settings should be reasonable so that
players' first experience with a role is positive and they don't just
end up hating the role because of them.

This setup (`Can't win after they died` OFF +
`Everyone knows who the Workaholic is` ON) also matches the original
Workaholic behavior from TOH_Y.

### CODE REVIEW

**Comment by KARPED1EM** [comment]
as my point of view, give any advice to players is not necessary, how to play game is a skill issue and its necessary to let players find out how each role work and how play each role in a better way

**Comment by KARPED1EM** [comment]
make they can win after death by default is good idea, coz its a big feature of workaholic.

**Comment by KARPED1EM** [comment]
so that everyone have to decide whether they should vote out workaholic or not

**Comment by Filipianosol** [comment]
> so this is just a advice send in first meeting?
Yeah, and makes Workaholic be able to win after death by default too.

I forgot to include the video, here:
https://user-images.githubusercontent.com/12639838/236742188-54d564e6-4194-44d3-93c7-baeb5a02f8c0.mp4

**Comment by Filipianosol** [comment]
> as my point of view, give any advice to players is not necessary, how to play game is a skill issue and its necessary to let players find out how each role work and how play each role in a better way

When I host and we have a Workaholic I always tell people they shouldn't kill the Workaholic so I wanted **an option** (hosts don't have to enable it) that would automate that. Would you accept it if I change it to default OFF? (right now `Advice at first meeting if alive, can win after death, ghost tasks ON` is ON by default)

**Comment by Filipianosol** [comment]
> make they can win after death by default is good idea, coz its a big feature of workaholic.
so that everyone have to decide whether they should vote out workaholic or not

Thanks. Yeah I agree.

**Comment by KARPED1EM** [comment]
Sorry, but true to my development philosophy. I probably didn't intend to give the player advice on how to play in the game. That's why this mod doesn't have my name under the ping tracker. I'd prefer to omit almost all hints that aren't skills or critical warnings.

**Comment by KARPED1EM** [comment]
Sorry, but true to my development philosophy. I probably didn't intend to give the player advice on how to play in the game. That's why this mod doesn't have my name under the ping tracker. I'd prefer to omit almost all hints that aren't skills or critical warnings.

**Comment by KARPED1EM** [comment]
Sorry, but true to my development philosophy. I probably didn't intend to give the player advice on how to play in the game. That's why this mod doesn't have my name under the ping tracker. I'd prefer to omit almost all hints that aren't skills or critical warnings.

**Comment by Filipianosol** [comment]
Fair. You said [this](https://github.com/KARPED1EM/TownOfHostEdited/pull/135/commits/2f95978b5f67ac712f055fc3986de7cc3eff7d6d) can be merged though, right?

**Comment by KARPED1EM** [comment]
oh internet here is too bad
seems like i sent three same msgs

**Comment by KARPED1EM** [comment]
> Fair. You said the [Workaholic: Can't win after they died: default OFF](https://github.com/KARPED1EM/TownOfHostEdited/pull/135/commits/2f95978b5f67ac712f055fc3986de7cc3eff7d6d) commit can be merged though, right?
> 

yes，this has been changed in dev version
and thanks for your pr

**Comment by KARPED1EM** [comment]
> Fair. You said the [Workaholic: Can't win after they died: default OFF](https://github.com/KARPED1EM/TownOfHostEdited/pull/135/commits/2f95978b5f67ac712f055fc3986de7cc3eff7d6d) commit can be merged though, right?
> 

yes，this has been changed in dev version
and thanks for your pr

**Comment by Filipianosol** [comment]
> oh internet here is too bad seems like i sent three same msgs

It's not your internet, GitHub is acting up for me now too. It also says I've pushed my changes but I don't see them on my fork when I go to the website. Other websites like YouTube work fine.
image

**Comment by Filipianosol** [comment]
> > Fair. You said the [Workaholic: Can't win after they died: default OFF](https://github.com/KARPED1EM/TownOfHostEdited/pull/135/commits/2f95978b5f67ac712f055fc3986de7cc3eff7d6d) commit can be merged though, right?
> 
> yes，this has been changed in dev version and thanks for your pr

Thanks for mering it!

**Comment by KARPED1EM** [comment]
> > oh internet here is too bad seems like i sent three same msgs
> 
> It's not your internet, GitHub is acting up for me now too. image Sending messages takes a long time too and it says I've pushed my changes (it's something else than this Workaholic update) but I don't see them on my fork when I go to the website. Other websites like YouTube work fine.

lol i cant even delete my repeated comment

**Comment by Filipianosol** [comment]
lol

**Pull request closed without merging**
